language: node_js
node_js:
    - "4.1"
    - "4.0"
    - "5"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test
before_script:
    - npm install
    - npm install jshint
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - "jshint *.js lib"
after_script:
    - npm run-script build
    - npm run-script test-coveralls
    - cd test/node && npm install && node app.js

