language: node_js
node_js:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm bootstrap
script:
    - npm run build
    - npm run test
after_script:
    - cd test/node && npm install && node app.js

