services:
    - xvfb
language: node_js
node_js:
    - "8"
    - "10"
    - "11"
    - "12"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    install:
    - npm install
script:
    - npm run-script build
    - npm run-script test-coveralls
after_script:
    - cd test/node && npm install && node app.js
